version: '3.8'

services:
  server:
    build: ./server
    container_name: python_socket_server
    ports:
      - "12345:12345"
    stdin_open: true
    tty: true

  client:
    build: ./client
    container_name: python_socket_client
    depends_on:
      - server
    stdin_open: true
    tty: true